# Class No 1

In [3]:
import numpy as np

data = [1,2,3,4,5,6]
data1 = np.array(data)
print(data1)

print(f"normal list: {data *2}")
print(f"np array: {data1 * 2}")

data3 = np.zeros(6)
print(data3)

data4 = np.ones(6)
print(data4)

data5 = np.empty(6)
print(data5)

data6 = np.arange(1,6)
print(data6)

print(np.ones((3,3)))
txt = ["abc","def","ghi","jkl"]
print(np.array(data).reshape)

[1 2 3 4 5 6]
normal list: [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
np array: [ 2  4  6  8 10 12]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[1 2 3 4 5]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<built-in method reshape of numpy.ndarray object at 0x000002B949F88580>


# Class 2

-> Practice nltk library

In [63]:
text = """Most. of this book uses high-level tools. like. pandas.read_csv to read data files from
disk into Python data structures. However, it\’s Mr. important to understand the basics of
how to work with files in Python. Fortunately\, it’s very simple, which is one reason
why Python is so popular for text and file munging? myhkjajs kajskdd kaksjd? hkjskajdjjkddddaas"""

In [72]:
data = np.array(text.split(". "))

In [91]:
print(data)
print("-------------")
fn = np.vectorize(len)

# np.vectorize take any function and apply individual all element of the numpy arry....
# in python we store function any variables.

# print(fn())
print(data[fn(data)<5])
print(data[( np.vectorize(len)) (data) <5])

['Most' 'of this book uses high-level tools' 'like'
 'pandas.read_csv to read data files from\ndisk into Python data structures'
 'However, it\\’s Mr'
 'important to understand the basics of\nhow to work with files in Python'
 'Fortunately\\, it’s very simple, which is one reason\nwhy Python is so popular for text and file munging? myhkjajs kajskdd kaksjd? hkjskajdjjkddddaas']
-------------
['Most' 'like']
['Most' 'like']


In [59]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array(4)
arr3 = arr*arr2
print(arr3)

[[ 4  8 12 16]
 [20 24 28 32]]


# fancy indexing


In [105]:
ar = np.array([12,45,59,-89,0,0,4,5,8])
print(ar)
print(ar[[4,5,6]])

[ 12  45  59 -89   0   0   4   5   8]
[0 0 4]


# where

In [94]:
salary = np.array([0,-1,3000,70000,30000])
np.where(salary<=0,25000,salary)

array([25000, 25000,  3000, 70000, 30000])

# Mathematical and static methods

In [96]:
print(np.cumsum(ar))
print(np.cumproduct(ar))

[ 12  57 116 205 239 242 246 251 259]
[        12        540      31860    2835540   96408360  289225080
 1156900320 1489534304 -968627456]


In [106]:
brr = ar>10
print(brr)
print(np.sum(brr))
print(ar.sum())
print(ar.all())

[ True  True  True False False False False False False]
3
44
False


# Save or Load

-> npz means multiple arry save in one file
-> here a = arr where a is key and arr is value that is array

In [113]:
np.savez('arrays.npz', a = ar)
arr12 = np.load('arrays.npz')
print(arr12['a'])

[ 12  45  59 -89   0   0   4   5   8]


# Linear Algebra


# Converting 2d to array

In [126]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[7,8,9,0],[1,2,3,4]])
c = np.concatenate([a,b],axis=0)
print('c',c)
print('hstack',np.vstack([a,b]))

c [[1 2 3 4]
 [5 6 7 8]
 [7 8 9 0]
 [1 2 3 4]]
hstack [[1 2 3 4]
 [5 6 7 8]
 [7 8 9 0]
 [1 2 3 4]]


In [120]:
#hstack
#vstack
#important


In [131]:
print(ar)
print("Split: ", np.split(ar,[1,3,6]))

[ 12  45  59 -89   0   0   4   5   8]
Split:  [array([12]), array([45, 59]), array([-89,   0,   0]), array([4, 5, 8])]


# CLASS N0 3

In [24]:
import numpy as np
ndarray = np.array(
                    [
                        [[111, 112, 113, 114], [121, 122, 123, 124], [131, 132, 133, 134]],
                        [[211, 212, 213, 214], [221, 222, 223, 224], [231, 232, 233, 234]],
                        [[311, 312, 313, 314], [321, 322, 323, 324], [331, 332, 333, 334]],
                        [[411, 412, 413, 414], [421, 422, 423, 424], [431, 432, 433, 434]]
                    ]
                  )
print(ndarray)
print("ndim :", ndarray.ndim, "shape :", ndarray.shape)
print(ndarray[2, 2, 2])

[[[111 112 113 114]
  [121 122 123 124]
  [131 132 133 134]]

 [[211 212 213 214]
  [221 222 223 224]
  [231 232 233 234]]

 [[311 312 313 314]
  [321 322 323 324]
  [331 332 333 334]]

 [[411 412 413 414]
  [421 422 423 424]
  [431 432 433 434]]]
ndim : 3 shape : (4, 3, 4)
333


In [34]:
print(len(ndarray))

4


# Images Processing

In [3]:

import numpy as np
import matplotlib.pylab as plt   # For image reading

def plti(im, h=8, **kwargs):
    """
    Helper function to plot an image.
    """
    y = im.shape[0]
    x = im.shape[1]
    w = (y/x) * h
    plt.figure(figsize=(w,h))
    plt.imshow(im, interpolation="none", **kwargs)
    plt.axis('off')
    input('press <ENTER> to continue')
# %matplotlib inline
im = plt.imread("bbaa.png")
print(type(im ) )
plti(im)
im = im[400:3800,:2000,:]
plti(im)
print( im.shape )
print(im[:5, :10, :10])

im = im[400:3800,:2000,:]
plti(im)

FileNotFoundError: [Errno 2] No such file or directory: 'bbaa.png'

# PANDAS

numpy 1 dimensional array = pandas series

In [37]:
import pandas as pd

ser = pd.Series([2,4,5,-7])
print(ser)

0    2
1    4
2    5
3   -7
dtype: int64


In [39]:
val = pd.Series([100,200,300,400])
print(val)
print(val.values)
print(val.index)

0    100
1    200
2    300
3    400
dtype: int64
[100 200 300 400]
RangeIndex(start=0, stop=4, step=1)


In [46]:
val = pd.Series([100,200,300,400,500], index = ['a','b','c','d','e'], name = 'client data')
print(val)
print(val > 200)
print(val[val > 200])
print(val * 2)

a    100
b    200
c    300
d    400
e    500
Name: client data, dtype: int64
a    False
b    False
c     True
d     True
e     True
Name: client data, dtype: bool
c    300
d    400
e    500
Name: client data, dtype: int64
a     200
b     400
c     600
d     800
e    1000
Name: client data, dtype: int64


In [10]:
import pandas as pd
orders = pd.Series([10,8,9,5,15,0,0], index = ['Mon','Tues','Wed','thres','Fri','Sat','Sun'], name="Weekly Orders")
print(orders)

new_order = 2 * orders
# print("Wednesday: ",new_order['Wed'],"\nFriday: ",new_order['Fri'])
print(new_order[['Wed','Fri']])

Mon      10
Tues      8
Wed       9
thres     5
Fri      15
Sat       0
Sun       0
Name: Weekly Orders, dtype: int64
Wed    18
Fri    30
Name: Weekly Orders, dtype: int64


## Class 4

In [2]:
import os 

import PIL as pil

def imageToNp(imageName):
      #cheak if the file is really an image 
      try:
          npa = pil.Image (imageName)
          return npa
      except(#trap valid exception name is better):
          print("Valid Error")
path, dirs, files = next(os.walk("/Download/pics"))
file_count = len(files)
image_array = np.zeros(file_count. 200, 200, 3)

for _,_ files in next(os.walk("/Download/pics")):
    idx = 0
    for file in files:
        image_aray =(idx , imageToNp(file)
        idx = idx + 1

SyntaxError: invalid syntax (<ipython-input-2-546538212205>, line 12)

# Assaignment
folder of pics containing name "photos".
help with coding guidline form search in google
direct store image in numpy array

In [13]:
state = {"Sindh": 2000, "KPK": 1000, "Punjab": 4000, "Balochistan": 3500}

tax_state = pd.Series(state, index = ["Punjab", "Sindh", "KPK", "Balochistan", "GB"])
print(tax_state)
tax_state['GB'] = 7000
print(tax_state)

Punjab         4000.0
Sindh          2000.0
KPK            1000.0
Balochistan    3500.0
GB                NaN
dtype: float64
Punjab         4000.0
Sindh          2000.0
KPK            1000.0
Balochistan    3500.0
GB             7000.0
dtype: float64


In [38]:
import pandas as pd
apple = pd.Series([1,2,3,4], ["a","b","c","d"])
orange = pd.Series([3,4,5,1], ["e","f","g","h"])
banana = pd.Series([])

data = {"Apple": apple, "Orange": orange}

fruit_df = pd.DataFrame(data)
print(fruit_df)

   Apple  Orange
a    1.0     NaN
b    2.0     NaN
c    3.0     NaN
d    4.0     NaN
e    NaN     3.0
f    NaN     4.0
g    NaN     5.0
h    NaN     1.0
